---
abstract: 'There is Brik for that.'
author:
  - 'GomoR <gomor_at_metabrik.org>'
build_requires: {}
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Metabrik
provides:
  Metabrik:
    file: lib/Metabrik.pm
    version: '1.01'
  Metabrik::Core::Context:
    file: lib/Metabrik/Core/Context.pm
  Metabrik::Core::Global:
    file: lib/Metabrik/Core/Global.pm
  Metabrik::Core::Log:
    file: lib/Metabrik/Core/Log.pm
  Metabrik::Core::Shell:
    file: lib/Metabrik/Core/Shell.pm
  Metabrik::Shell::Command:
    file: lib/Metabrik/Shell/Command.pm
  Metabrik::Shell::History:
    file: lib/Metabrik/Shell/History.pm
  Metabrik::Shell::Rc:
    file: lib/Metabrik/Shell/Rc.pm
  Metabrik::Shell::Script:
    file: lib/Metabrik/Shell/Script.pm
resources:
  license: http://opensource.org/licenses/BSD-3-Clause
version: '1.01'
