---
abstract: 'There is Brik for that.'
author:
  - 'GomoR <gomor_at_metabrik.org>'
build_requires: {}
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Metabrik
provides:
  Metabrik:
    file: lib/Metabrik.pm
    version: '1.04'
  Metabrik::Core::Context:
    file: lib/Metabrik/Core/Context.pm
    version: '1.04'
  Metabrik::Core::Global:
    file: lib/Metabrik/Core/Global.pm
    version: '1.04'
  Metabrik::Core::Log:
    file: lib/Metabrik/Core/Log.pm
    version: '1.04'
  Metabrik::Core::Shell:
    file: lib/Metabrik/Core/Shell.pm
    version: '1.04'
  Metabrik::Shell::Command:
    file: lib/Metabrik/Shell/Command.pm
    version: '1.04'
  Metabrik::Shell::History:
    file: lib/Metabrik/Shell/History.pm
    version: '1.04'
  Metabrik::Shell::Rc:
    file: lib/Metabrik/Shell/Rc.pm
    version: '1.04'
  Metabrik::Shell::Script:
    file: lib/Metabrik/Shell/Script.pm
    version: '1.04'
requires:
  Class::Gomor: '0'
  Cwd: '0'
  Data::Dump: '0'
  File::Find: '0'
  File::HomeDir: '0'
  IO::All: '0'
  Lexical::Persistence: '0'
  Module::Reload: '0'
  Term::ANSIColor: '0'
  Term::Shell: '0'
  local::lib: '0'
  perl: v5.6.1
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: '1.04'
